on: [push, pull_request]
jobs:
  catfact:
    runs-on: ubuntu-latest
    name: Adds a cat fact
    steps:
     - uses: actions/checkout@main
     - name: catfact
       uses: itchison/CatFactAction/action@main